# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev1+gdd4c1f7.d20230630'
__version_tuple__ = version_tuple = (0, 1, 'dev1', 'gdd4c1f7.d20230630')
