# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev2+g123259e.d20230630'
__version_tuple__ = version_tuple = (0, 1, 'dev2', 'g123259e.d20230630')
