hydra:
  run:
    dir: data/outputs/${dataset.name}/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: data/outputs/${dataset.name}/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${dataset.split.name}/${dataset.preprocess.norm}_norm/fold_${dataset.split.id}
  sweeper:
    params:
      dataset.split.id: 1,2,3,4,5,6,7,8,9,10
defaults:
  - dataset: GDSCv2DepMap
  - model: ScreenDL
  - _self_
output:
  log: logs
  