hydra:
  run:
    dir: data/outputs/${model.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: false
  sweep:
    dir: data/outputs/${model.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra:job.num}
defaults:
  - _self_
  - dataset: gdsc_cell_line
  - model: screendl
output:
  log_dir: ${hydra:run.dir}/logs
  out_dir: ${hydra:run.dir}/results
  save_model: true